name: Folia 1.21.4 Build 

on:
  push:
    branches: [ "ver/1.21.4" ]
  workflow_dispatch:
  #workflow_run:
    #workflows: ["Automatically update Folia commit"]
    #types:
      #- completed

jobs:
  compile_1_21_4_core_jar:
    runs-on: windows-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyAllPatches
   
      - name: Build MojmapPaperclip
        run: ./gradlew createMojmapPaperclipJar

      - name: Upload Folia jar
        uses: actions/upload-artifact@v4
        with:
           name: Folia jar
           path: "folia-server/build/libs/*"
         
      - name: Make release
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "Folia 1.21.4 release"
          automatic_release_tag: "latest_1.21.4"
          files: "folia-server/build/libs/*"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
